name: Deploy Lambda Functions

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for all branches

      - name: Set Up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'
          cache: 'pip' # caching pip dependencies

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Identify Changed Functions
        run: |
          set -e  # Exit immediately if a command exits with a non-zero status
          
          echo "Checking for commits in the repository..."
          if [ "$(git rev-list --count HEAD)" -eq 0 ]; then
            echo "No commits found in the repository."
            echo "changed_dirs=" >> $GITHUB_ENV
            exit 0
          fi

          echo "Getting the latest commit hash..."
          LATEST_COMMIT=$(git rev-parse HEAD)
          echo "LATEST_COMMIT: $LATEST_COMMIT"

          echo "Getting the previous commit hash..."
          PREV_COMMIT=$(git rev-parse HEAD~1 2>/dev/null || echo "")
          echo "PREV_COMMIT: $PREV_COMMIT"

          echo "Getting changed files between the latest and previous commits..."
          CHANGED_FILES=$(git diff --name-only "$PREV_COMMIT" "$LATEST_COMMIT")
          echo "CHANGED_FILES: $CHANGED_FILES"

          echo "Extracting unique directories from changed files..."
          CHANGED_DIRS=$(echo "$CHANGED_FILES" | awk -F'/' '{print $1"/"$2"/"$3}' | sort -u | grep -v '^$')
          echo "CHANGED_DIRS: $CHANGED_DIRS"

          VALID_DIRS=""
          for dir in $CHANGED_DIRS; do
            echo "Checking directory: $dir"
            if [ -f "$dir/lambda_function.py" ] && [ -f "$dir/requirements.txt" ]; then
              VALID_DIRS="$VALID_DIRS $dir"
              echo "Valid directory: $dir"
            else
              echo "Invalid directory (missing files): $dir"
            fi
          done

          echo "Valid directories: $VALID_DIRS"

          if [ -n "$VALID_DIRS" ]; then
            # Set changed_dirs as a comma-separated list for processing later
            echo "changed_dirs=$(echo "$VALID_DIRS" | tr ' ' ',')" >> $GITHUB_ENV
          else
            echo "changed_dirs=" >> $GITHUB_ENV
          fi

      - name: Deploy Changed Functions
        if: env.changed_dirs != ''
        run: |
          set -e  # Exit immediately if a command exits with a non-zero status

          echo "Deploying changed functions..."
          IFS=',' read -r -a function_dirs <<< "$changed_dirs"  # Split changed_dirs into an array
          
          for function_dir in "${function_dirs[@]}"; do
            echo "Processing $function_dir"
            
            # Check if directory exists before changing into it
            if [ ! -d "$function_dir" ]; then
              echo "Directory does not exist: $function_dir"
              continue  # Skip this iteration if the directory doesn't exist
            fi
            
            pushd "$function_dir"
            
            # Set up a dedicated virtual environment
            python -m venv env
            source env/bin/activate

            # Install dependencies if requirements.txt exists
            mkdir -p package
            
            if [ -f requirements.txt ]; then
              pip install --target ./package/ -r requirements.txt || { echo 'Failed to install dependencies'; exit 1; }
            fi
            
            # Add Lambda handler to package
            cp lambda_function.py package/

            # Package everything into a zip file
            cd package || { echo 'Failed to enter package directory'; exit 1; }
            zip -r ../function.zip .
            cd ..

            # Extract the function name from the directory path (assuming it's the last part of the path)
            FUNCTION_NAME=$(basename "$function_dir")
            echo "Updating Lambda function: $FUNCTION_NAME"

            # Update the Lambda function code in AWS
            aws lambda update-function-code --function-name "$FUNCTION_NAME" --zip-file fileb://function.zip --region "${{ secrets.AWS_REGION }}" || { echo 'Failed to update Lambda function'; exit 1; }

            # Clean up
            rm -rf env package function.zip
            
            popd
          done

